services:
  paqtracker-planificador:
    build: .
    image: paqtracker-planificador:0.5.0
    env_file:
      - path: .env
        required: false
    volumes:
      - ./datos:/app/datos:ro
    networks:
      - paqtracker-red

networks:
  paqtracker-red:
    name: paqtracker-red
